version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(filename)s %(funcName)s %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

root:
    level: INFO
    handlers: [console]